version: "3"
services:
    db_server:
        image: kamatimaru/mysql80-ja:latest
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cve
    cache_server:
        image: redis:6.0.4
        ports:
            - "6379:6379"