# Generated by Django 3.0.7 on 2020-07-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE FULLTEXT INDEX cve_text_for_search_index ON cve_full_text_search (cve_text_for_search)",
            "DROP INDEX cve_text_for_search_index ON cve_full_text_search",
        ),
    ]
