# Generated by Django 3.1.6 on 2021-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200703_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
